
services:
  postgres_primary:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - ./tmp/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8888:8888
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8888
    depends_on:
      - postgres_primary

networks:
  default:
    driver: bridge
    name: webapp